-- Migration: 001_init.sql
-- Description: Initial schema for ops-pipeline database
-- Creates all core tables with constraints and indexes

-- ============================================================================
-- MIGRATION TRACKING TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS schema_migrations (
    version TEXT PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================================
-- INBOUND EVENTS RAW TABLE
-- Stores raw RSS feed items before classification
-- ============================================================================
CREATE TABLE IF NOT EXISTS inbound_events_raw (
    id BIGSERIAL PRIMARY KEY,
    event_uid TEXT NOT NULL UNIQUE,  -- sha256 hash of guid/link/title+published
    published_at TIMESTAMPTZ NULL,   -- original publish time from feed
    source TEXT NULL,                 -- feed URL or source identifier
    title TEXT NOT NULL,              -- headline/title
    link TEXT NULL,                   -- URL to original article
    summary TEXT NULL,                -- article summary/description
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),  -- when we fetched it
    processed_at TIMESTAMPTZ NULL     -- when classification completed
);

-- Indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_inbound_raw_processed 
    ON inbound_events_raw(processed_at) 
    WHERE processed_at IS NULL;  -- Find unprocessed items efficiently

CREATE INDEX IF NOT EXISTS idx_inbound_raw_published 
    ON inbound_events_raw(published_at DESC);

CREATE INDEX IF NOT EXISTS idx_inbound_raw_fetched 
    ON inbound_events_raw(fetched_at DESC);

-- ============================================================================
-- INBOUND EVENTS CLASSIFIED TABLE
-- Stores sentiment analysis results and extracted tickers
-- ============================================================================
CREATE TABLE IF NOT EXISTS inbound_events_classified (
    id BIGSERIAL PRIMARY KEY,
    raw_event_id BIGINT NOT NULL REFERENCES inbound_events_raw(id) ON DELETE CASCADE,
    tickers TEXT[] NOT NULL DEFAULT '{}',   -- extracted stock symbols
    sentiment_label TEXT NOT NULL,           -- positive/negative/neutral
    sentiment_score DOUBLE PRECISION NOT NULL,  -- confidence score
    event_type TEXT NULL,                    -- future: earnings/merger/etc
    urgency TEXT NULL,                       -- future: breaking/routine
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(raw_event_id)  -- Each raw event classified only once
);

-- Indexes for querying classified events
CREATE INDEX IF NOT EXISTS idx_classified_tickers 
    ON inbound_events_classified USING GIN(tickers);

CREATE INDEX IF NOT EXISTS idx_classified_created 
    ON inbound_events_classified(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_classified_sentiment 
    ON inbound_events_classified(sentiment_label, created_at DESC);

-- ============================================================================
-- FEED STATE TABLE
-- Tracks RSS feed metadata for efficient polling (ETags, Last-Modified)
-- ============================================================================
CREATE TABLE IF NOT EXISTS feed_state (
    feed_url TEXT PRIMARY KEY,
    etag TEXT NULL,                          -- HTTP ETag for conditional requests
    last_modified TEXT NULL,                 -- HTTP Last-Modified header
    last_seen_published TIMESTAMPTZ NULL,    -- Most recent article publish time
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================================
-- LANE TELEMETRY TABLE
-- Stores market OHLCV candle data
-- ============================================================================
CREATE TABLE IF NOT EXISTS lane_telemetry (
    ticker TEXT NOT NULL,
    ts TIMESTAMPTZ NOT NULL,                 -- candle timestamp
    open DOUBLE PRECISION NOT NULL,
    high DOUBLE PRECISION NOT NULL,
    low DOUBLE PRECISION NOT NULL,
    close DOUBLE PRECISION NOT NULL,
    volume BIGINT NULL,
    PRIMARY KEY (ticker, ts)
);

-- Index for efficient time-series queries (most recent first)
CREATE INDEX IF NOT EXISTS idx_telemetry_ticker_ts 
    ON lane_telemetry(ticker, ts DESC);

-- ============================================================================
-- DISPATCH RECOMMENDATIONS TABLE
-- Stores trading signals generated by signal engine
-- ============================================================================
CREATE TABLE IF NOT EXISTS dispatch_recommendations (
    id BIGSERIAL PRIMARY KEY,
    ts TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ticker TEXT NOT NULL,
    action TEXT NOT NULL CHECK (action IN ('BUY', 'SELL')),
    confidence DOUBLE PRECISION NULL,        -- signal confidence 0-1
    reason JSONB NOT NULL DEFAULT '{}'::JSONB,  -- why this signal was generated
    status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'EXECUTED', 'CANCELLED')),
    executed_at TIMESTAMPTZ NULL,
    filled_price DOUBLE PRECISION NULL,      -- execution price
    shares DOUBLE PRECISION NULL             -- position size
);

-- Indexes for dispatcher queries
CREATE INDEX IF NOT EXISTS idx_recommendations_status_ts 
    ON dispatch_recommendations(status, ts DESC);

CREATE INDEX IF NOT EXISTS idx_recommendations_ticker_ts 
    ON dispatch_recommendations(ticker, ts DESC);

CREATE INDEX IF NOT EXISTS idx_recommendations_executed 
    ON dispatch_recommendations(executed_at DESC) 
    WHERE executed_at IS NOT NULL;

-- ============================================================================
-- GRANT PERMISSIONS (if needed for specific users/roles)
-- ============================================================================
-- Add any specific GRANT statements here if needed

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================
-- Run these to verify migration succeeded:
-- 
-- 1. List all tables:
--    SELECT tablename FROM pg_tables WHERE schemaname = 'public' ORDER BY tablename;
--
-- 2. Check table row counts:
--    SELECT 'inbound_events_raw' as table_name, COUNT(*) as row_count FROM inbound_events_raw
--    UNION ALL SELECT 'inbound_events_classified', COUNT(*) FROM inbound_events_classified
--    UNION ALL SELECT 'feed_state', COUNT(*) FROM feed_state
--    UNION ALL SELECT 'lane_telemetry', COUNT(*) FROM lane_telemetry
--    UNION ALL SELECT 'dispatch_recommendations', COUNT(*) FROM dispatch_recommendations;
--
-- 3. Verify indexes:
--    SELECT indexname, tablename FROM pg_indexes WHERE schemaname = 'public' ORDER BY tablename, indexname;
--
-- 4. Check foreign keys:
--    SELECT conname, conrelid::regclass, confrelid::regclass 
--    FROM pg_constraint WHERE contype = 'f';
--
-- 5. Verify check constraints:
--    SELECT conname, conrelid::regclass, pg_get_constraintdef(oid) 
--    FROM pg_constraint WHERE contype = 'c';
--
-- 6. Check applied migrations:
--    SELECT * FROM schema_migrations ORDER BY applied_at;
