#!/usr/bin/env python3
"""
Manual SQL cleanup - provides SQL commands to run via existing tools.
Since we can't run UPDATE directly, we'll use the sync script approach.
"""

print("=" * 80)
print("PHANTOM POSITION CLEANUP - MANUAL SQL APPROACH")
print("=" * 80)
print()
print("Since direct database UPDATE is restricted, here are your options:")
print()
print("=" * 80)
print("OPTION 1: Use the sync script (RECOMMENDED)")
print("=" * 80)
print()
print("The sync script can identify and fix phantom positions:")
print()
print("  python3 scripts/sync_positions_with_alpaca.py")
print()
print("This script will:")
print("  1. Query Alpaca for actual positions")
print("  2. Query database for recorded positions")
print("  3. Identify mismatches (phantom positions)")
print("  4. Offer to close phantom positions in database")
print()
print("=" * 80)
print("OPTION 2: SQL via psql (if you have direct access)")
print("=" * 80)
print()
print("If you have psql access to the database, run:")
print()
print("UPDATE active_positions")
print("SET ")
print("    status = 'closed',")
print("    close_reason = 'manual_reconciliation',")
print("    closed_at = NOW(),")
print("    exit_price = entry_price,")
print("    current_pnl_dollars = 0,")
print("    current_pnl_percent = 0")
print("WHERE status IN ('open', 'closing')")
print("AND id IN (16, 24, 13, 21, 19, 32, 33);")
print()
print("=" * 80)
print("OPTION 3: Check if positions are already closed")
print("=" * 80)
print()
print("First, let's verify which positions actually need cleanup.")
print("Run this to check current status:")
print()
print("  python3 -c \"")
print("import boto3, json")
print("lambda_client = boto3.client('lambda', region_name='us-west-2')")
print("response = lambda_client.invoke(")
print("    FunctionName='ops-pipeline-db-query',")
print("    Payload=json.dumps({")
print("        'sql': '''SELECT id, ticker, option_symbol, status, close_reason ")
print("                  FROM active_positions ")
print("                  WHERE id IN (16, 24, 13, 21, 19, 32, 33) ")
print("                  ORDER BY id'''")
print("    })")
print(")")
print("result = json.loads(response['Payload'].read())")
print("print(json.dumps(result, indent=2))")
print("\"")
print()
print("=" * 80)
print()
print("RECOMMENDED: Use Option 1 (sync script) as it's the safest approach!")
print()
